# Generated by Django 3.1.3 on 2020-12-10 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maliapp', '0002_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_active',
            new_name='is_tradee',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_staff',
            new_name='is_trader',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='status',
        ),
    ]
