# Generated by Django 3.1.3 on 2020-12-10 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maliapp', '0003_auto_20201210_1524'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_tradee',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_trader',
            new_name='is_staff',
        ),
    ]
